### DISCUSSION TITLE
How can I access the "schemaAt" method for unit testing migrations

### DISCUSSION THREAD

**Discussion by MiguelSOliveira** [simolus3/drift#1048] [Q&A] [answered]
I'm trying to follow the documentation and in the category `Verifying data integrity` of https://moor.simonbinder.eu/docs/advanced-features/migrations/, we call `verifier.schemaAt` to add rawData to the database for testing.

However, from what I can see this was added in this commit:
https://github.com/simolus3/moor/tree/6c913a481145019a8c37c3d6f2d4480ac884f83e

Which was introduced with version:
3.5.0-dev

I've tried adding this commit manually like so:

```
moor:
    git:
      url: git@github.com:simolus3/moor.git
      path: moor
      ref: 6c913a481145019a8c37c3d6f2d4480ac884f83e

moor_generator:
    git:
      url: git@github.com:simolus3/moor.git
      path: moor_generator
      ref: 6c913a481145019a8c37c3d6f2d4480ac884f83e
```

But I get the following error:

```
Because every version of moor_generator from git depends on moor from hosted and projectName depends on moor from git, moor_generator from git is forbidden.
So, because projectName depends on moor_generator from git, version solving failed.
Running "flutter pub get" in projectName...
pub get failed (1; So, because projectName depends on moor_generator from git, version solving failed.)
```

How can I access this `schemaAt` method? It's not in the released 3.4.0 version of moor.

**Comment by MiguelSOliveira** [comment, marked as answer]
This particular problem is solved by doing this:

```
dependency_overrides:
  moor_generator:
    git:
      url: git@github.com:simolus3/moor.git
      path: moor_generator
      ref: 6c913a481145019a8c37c3d6f2d4480ac884f83e
  moor:
    git:
      url: git@github.com:simolus3/moor.git
      path: moor
      ref: 6c913a481145019a8c37c3d6f2d4480ac884f83e
```

However, can anyone confirm this is the right commit for this functionality? I'm getting errors that may be explained by not pulling the right commit.

Am I missing something or is the documentation not accurate in this aspect?

**Reply by simolus3** [reply]
3.5.0 has never been released, it was included in the current 4.0 pre-release. If you don't want to use that the git overrides should be fine too.

**Reply by MiguelSOliveira** [reply]
Hey simolus, thank you for the answer. Are you saying that for this functionality I need the v4.0 pre-release?

And the overrides give me the following error that I'm not sure are related to the test or not:

```
../.pub-cache/git/moor-6c913a481145019a8c37c3d6f2d4480ac884f83e/moor_generator/lib/src/services/schema/find_differences.dart:174:7:
Error: The method 'enforceEqualIterable' isn't defined for the class 'FindSchemaDifferences'.
 - 'FindSchemaDifferences' is from 'package:moor_generator/src/services/schema/find_differences.dart'
 ('../.pub-cache/git/moor-6c913a481145019a8c37c3d6f2d4480ac884f83e/moor_generator/lib/src/services/schema/find_differences.dart').
Try correcting the name to the name of an existing method, or defining a method named 'enforceEqualIterable'.
      enforceEqualIterable(ref.constraints, act.constraints);
      ^^^^^^^^^^^^^^^^^^^^
../.pub-cache/git/moor-6c913a481145019a8c37c3d6f2d4480ac884f83e/moor_generator/lib/src/services/schema/find_differences.dart:176:41:
Error: The getter 'spanOrNull' isn't defined for the class 'List<ColumnConstraint>'.
 - 'List' is from 'dart:core'.
 - 'ColumnConstraint' is from 'package:sqlparser/src/ast/ast.dart'
 ('../.pub-cache/hosted/pub.dartlang.org/sqlparser-0.11.0/lib/src/ast/ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'spanOrNull'.
      final firstSpan = ref.constraints.spanOrNull?.text ?? '';
                                        ^^^^^^^^^^
../.pub-cache/git/moor-6c913a481145019a8c37c3d6f2d4480ac884f83e/moor_generator/lib/src/services/schema/find_differences.dart:177:42:
Error: The getter 'spanOrNull' isn't defined for the class 'List<ColumnConstraint>'.
 - 'List' is from 'dart:core'.
 - 'ColumnConstraint' is from 'package:sqlparser/src/ast/ast.dart'
 ('../.pub-cache/hosted/pub.dartlang.org/sqlparser-0.11.0/lib/src/ast/ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'spanOrNull'.
      final secondSpan = act.constraints.spanOrNull?.text ?? '';

```

**Reply by simolus3** [reply]
> Are you saying that for this functionality I need the v4.0 pre-release?

The overrides should work. If you want to use a version from pub, you'd have to use the 4.0 pre-release.

```yaml
dependencies:
  moor: ^4.0.0-nullsafety.0
dev_dependencies:
  moor_generator: ^4.0.0-dev
```

Even though it's a pre-release, I've tested it as if it were a regular one and there will only be a very minor breaking change between that and the actual release, so using it should be ok.

> And the overrides give me the following error that I'm not sure are related to the test or not:

I think you would have to override the `sqlparser` package as well:

```yaml
  sqlparser:
    git:
      url: git@github.com:simolus3/moor.git
      path: sqlparser
      ref: 6c913a481145019a8c37c3d6f2d4480ac884f83e
```
