### DISCUSSION TITLE
`insert` always returns `int`

### DISCUSSION THREAD

**Discussion by ffpetrovic** [simolus3/drift#1222] [Q&A] [answered]
What if my model doesn't have an auto-increment `id` but uses a TextColumn with the default value being a generated uuid?
```dart
  TextColumn get id => text().clientDefault(() => _uuid.v4())();
```

I see in the [comment](https://github.com/simolus3/moor/blob/21cf78a361d502bfba9b225aa9359af06be0461b/moor/lib/src/runtime/query_builder/statements/insert.dart#L54) that it returns `rowid`. How can I get the full inserted row, after inserting a Companion/partial row, with my `id` (uuid) TextColumn?

**Comment by simolus3** [comment, marked as answer]
You can use [`insertReturning`](https://pub.dev/documentation/moor/latest/moor/InsertStatement/insertReturning.html) instead of `insert` to obtain a full row instance with the generated uuid.

Be aware that this requires a fairly recent sqlite3 version (at least 3.35.0). If you use `sqlite3_flutter_libs` you will have that version available, if you rely on the sqlite3 from the operating systems you probably don't.

**Reply by davidmartos96** [reply]
I would like to add on top of what Simon mentioned that, since you are using UUIDs you may as well generate it outside and pass it through the companion yourself, that way you would have it available beforehand.

**Reply by ffpetrovic** [reply]
Thanks for the answer guys.

@davidmartos96 

I'm already doing that, just hoping that the only reason companions exists is to allow for omitting "required" fields with default values using `clientDefault` because if so, this below looks fine, but let me know what you think

```dart
  // ...database
  Message createMessage(MessagesCompanion companion) {
    final id = _uuid.v4();

    return Message(
      id: id,
      content: companion.content.value,
    );
  }

  Future<void> insertMessage(Insertable<Message> message) async {
    await into(messages).insert(message);
  }
  ```
  
  I guess I'm concerned about instantiating a row class myself from an existing companion? Is that fine?

**Reply by simolus3** [reply]
> I guess I'm concerned about instantiating a row class myself from an existing companion? Is that fine?

I don't really see an issue with that as long as you can guarantee that all values will be known before an insert. That's not the case with auto-incrementing ids etc., but it should be fine here.

**Reply by ffpetrovic** [reply]
Perfect, thanks Simon, and thanks for the amazing work, you rock.

**Reply by ffpetrovic** [reply]
@simolus3  I'm getting `near "RETURNING": syntax error in "INSERT INTO` when using `insertReturning`, my flutter_sqlite_libs is on 0.4.3.

**Reply by simolus3** [reply]
Uh oh, are you on Android or iOS?

**Reply by ffpetrovic** [reply]
Android

**Reply by ffpetrovic** [reply]
```
  sqlite3:
    dependency: transitive
    description:
      name: sqlite3
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.1"
  sqlite3_flutter_libs:
    dependency: "direct main"
    description:
      name: sqlite3_flutter_libs
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.3"
```

Here's sqlite and sqlite_flutter_libs
