### DISCUSSION TITLE
Questions about Migrating to null-safety

### DISCUSSION THREAD

**Discussion by apoleo88** [simolus3/drift#1260] [Q&A] [answered]
I am updating to the last moor null safety, but I am not sure of the many things that changed.

I am using **encrypted_moor**
```
  moor: ^4.3.2
  encrypted_moor:
    git:
      url: https://github.com/simolus3/moor.git
      path: extras/encryption
```
```
  moor_generator:
        options:
          write_from_json_string_constructor: true
          mutable_classes: true
```

First of my worries: will be the data in my existing databases still be working flawlessly after the migration?

In my database dart I was defining methods as such:
`Future insertProfile(Profile entry) async => insert(profiles, entry);`

I had many methods like that, do I have to change them all using companions?
` Future insertProfile(ProfilesCompanion entry) async => insert(profiles, entry);`

But then I have to change everywhere I used the Class and instead use the Companions?
First I was simply doing:
```
Profile profile =  Profile(name: 'Abc');
profile.level = 3;
db.insertProfile( profile );
```
Now, I have to change every call to the database using companions instead?
```
ProfilesCompanion profile = ProfilesCompanion.insert(
  name: Value('Abc'),
);
profile.level = Value(3);
db.insertProfile( profile );
```

It is a very time-consuming migration, because being able to use the class row `Profile` allowed me to integrate it within my code. But now I have to differentiate when I am using ProfileCompanions to insert it, and where I have to use Profile because I am selecting one.

Also, the need to use Value() is super annoying, I have to update many and many queries. I somehow understand the need for it, but the boilerplate now became annoying.

Am I missing something? 
Do you have any suggestions on how to reduce the time of this migration?

Thank you.
