### DISCUSSION TITLE
Generate json serialized class using json_serializable that depend on moor generated data class

### DISCUSSION THREAD

**Discussion by salman731** [simolus3/drift#1266] [Q&A]
when I generate json serialized custome class using json_serializable package that generate on basis of data classes generated by moor it json_serializable package generate incomplete  code e.g

```dart
import 'package:json_annotation/json_annotation.dart';
import 'package:scribes_application/database/ScribeDatabase.dart';
import 'package:scribes_application/database/custom_models/TaxSetupMaster.dart';
import 'package:scribes_application/utils/constants/constants.dart';
import 'package:scribes_application/database/custom_models/ItemsInfo.dart';
import 'package:scribes_application/database/custom_models/CardSetupMaster.dart';

part 'Settings.g.dart';

@JsonSerializable(explicitToJson: true)
class Settings {
  @JsonKey(
    name: SettingJsonKeys.JSON_COUNTER_SETTINGS,
  )
  CounterSetting counterSettings;

  @JsonKey(name: SettingJsonKeys.JSON_ITEM_INFO)
  ItemsInfo itemsInfo;

  @JsonKey(name: SettingJsonKeys.JSON_SALES_POINT_SETUP_LIST)
  List<SalesPostingSetup> salesPostingSetupList;

  @JsonKey(name: SettingJsonKeys.JSON_STRINGS_LIST)
  List<Language> languageList;

  @JsonKey(name: SettingJsonKeys.JSON_WEIGHING_SCALE_SETUP)
  List<WeighingScaleSetup> weighingScaleSetupList;

  @JsonKey(name: SettingJsonKeys.JSON_TAX_SETUP_MASTER)
  TaxSetupMaster taxSetupMaster;

  @JsonKey(name: SettingJsonKeys.JSON_POS_USER_SETTINGS)
  List<UserSetting> userSettingList;

  @JsonKey(name: SettingJsonKeys.JSON_CARD_SETUP_MASTER)
  CardSetupMaster cardSetupMaster;

  @JsonKey(name: SettingJsonKeys.JSON_BENCH_LEVEL_LIST)
  List<BenchLevel> benchLevelList;

  @JsonKey(name: SettingJsonKeys.JSON_PRINTER_GROUPS)
  List<PrinterGroup> printerGroups;

  @JsonKey(name: SettingJsonKeys.JSON_SMS_SETTINGS)
  SmsSetting smsSettings;

  @JsonKey(name: SettingJsonKeys.JSON_SMS_FORMATS)
  List<SmsFormat> smsFormats;

  Settings(
      {this.counterSettings,
      this.itemsInfo,
      this.salesPostingSetupList,
      this.languageList,
      this.weighingScaleSetupList,
      this.taxSetupMaster,
      this.userSettingList,
      this.cardSetupMaster,
      this.benchLevelList,
      this.printerGroups,
      this.smsSettings,
      this.smsFormats});

  factory Settings.fromJson(Map<String, dynamic> json) => _$SettingsFromJson(json);

  Map<String, dynamic> toJson() => _$SettingsToJson(this);
}
```

**Comment by simolus3** [comment]
This requires some special build setup as described [here](https://moor.simonbinder.eu/docs/advanced-features/builder_options/#using-moor-classes-in-other-builders). I can help you write the right configuration. Depending on your exact use case, the config can be simpler than what's posted on the docs. Do you ever need `json_serializable` and `moor_generator` to write into the same part file? If you don't, we can simplify the config to just run `moor_generator` first.

**Reply by salman731** [reply]
I want to generate code first for moor and json serialization code on second. Can you share config in which moor_generator runs first and json serialize generator after that.

**Reply by simolus3** [reply]
Sure. You can create a [`build.yaml`](https://github.com/dart-lang/build/tree/master/build_config) file in your project's root (next to the pubspec of your app) with the following content:

```yaml
targets:
  # This target will emit .g.dart files for moor
  run_moor:
    auto_apply_builders: false
    builders:
      moor_generator|preparing_builder:
        enabled: true
      moor_generator:
        enabled: true
      source_gen|combining_builder:
        enabled: true
        generate_for:
          - lib/src/database/**  # Change this to only include your database files where moor creates code
  # This is the default target for build_runner. We change it so that depends on the moor target,
  # causing moor_generator to run first. Also, we have to disable moor builders here because
  # they shouldn't run twice!
  $default:
    dependencies: [ ':run_moor' ]
    builders:
      moor_generator|preparing_builder:
        enabled: false
      moor_generator:
        enabled: false
```

You can see the documentation of the `build_config` package for details on targets and builders. Basically, the idea here is that we have a target responsible for writing all files generated by moor. The default target is what `build_runner build` attempts to build, so we can make it depend on the moor target which will ensure the correct order.
In Dart's build system, two builders or targets are not allowed to create the same files. So, we tell the builder responsible for actually creating the `.g.dart` file from intermediary parts to only run on your database sources in the first target.

I think the configuration should work, but I haven't actually tried it. If you run into problems with it please let me know, then I'll try to setup a proper example with this.

**Reply by salman731** [reply]
Both source_gen:combining_builder and source_gen:combining_builder may output lib/Database/DatabaseDAO/**.g.dart. Potential outputs must be unique across all builders. See https://github.com/dart-lang/build/blob/master/docs/faq.md#why-do-builders-need-unique-outputs

**Reply by salman731** [reply]
I have facing above problem.

**Reply by simolus3** [reply]
Oh, I see. Can you add this to the `$default` target then:

```yaml
$default:
  builders:
    source_gen|combining_builder:
      generate_for:
        exclude:
           - lib/src/database/**  # onc again change this to point to your database files
```
