### DISCUSSION TITLE
Mistake in docs

### DISCUSSION THREAD

**Discussion by givip** [simolus3/drift#1378] [Show and tell]
[Code snippet in fragment](https://develop--moor.netlify.app/docs/advanced-features/builder_options/#using-moor-classes-in-other-builders) contains mistake.

`auto_apply_builders: false` is in the wrong level

Should be:

```
targets:
  $default:
    # disable the default generators, we'll only use the non-shared moor generator here
    auto_apply_builders: false
    builders:
      moor_generator|moor_generator_not_shared:
        enabled: true
        # If needed, you can configure the builder like this:
        # options:
        #   skip_verification_code: true
        #   use_experimental_inference: true
      # This builder is necessary for moor-file preprocessing. You can disable it if you're not
      # using .moor files with type converters.
      moor_generator|preparing_builder:
        enabled: true
  
  run_built_value:
    dependencies: ['your_package_name']
    builders:
      # Disable moor builders. By default, those would run on each target
      moor_generator:
        enabled: false
      moor_generator|preparing_builder:
        enabled: false
      # we don't need to disable moor_generator_not_shared, because it's disabled by default
```
