### DISCUSSION TITLE
Using git path as a dependency fails.

### DISCUSSION THREAD

**Discussion by YeungKC** [simolus3/drift#1523] [Q&A] [answered]
I need some recent changes, so I'm use git path as a dependency, but I got some error.....

config: 
```yaml
...
  drift:
    git:
      url: https://github.com/simolus3/moor.git
      ref: develop
      path: drift
...
  drift_dev:
    git:
      url: https://github.com/simolus3/moor.git
      ref: develop
      path: drift_dev
...
```

log:

```
Because every version of drift_dev from git depends on drift from hosted and flutter_app depends on drift from git, drift_dev from git is forbidden.
So, because flutter_app depends on drift_dev from git, version solving failed.
Running "flutter pub get" in flutter-app...                             
pub get failed (1; So, because flutter_app depends on drift_dev from git, version solving failed.)
```

**Comment by simolus3** [comment, marked as answer]
This is expected and not something I can reasonably change. You could use `dependency_overrides` instead:

```yaml
dependency_overrides:
  drift:
    git:
      url: https://github.com/simolus3/moor.git
      ref: develop
      path: drift
...
  drift_dev:
    git:
      url: https://github.com/simolus3/moor.git
      ref: develop
      path: drift_dev
```
