### DISCUSSION TITLE
Sqlite 3.36 locally but Sqlite 3.32 on CodeMagic

### DISCUSSION THREAD

**Discussion by svarlet** [simolus3/drift#1745] [Q&A] [answered]
Hi,

I need help to fix my integration tests. They pass locally but fail on our build server. 
An exception is thrown when we use INSERT RETURNING. I immediately knew that was related to the version of sqlite. 
A few print statements later, I confirmed that my integration tests create an (in memory) sqlite db with sqlite 3.36. That supports the RETURNING clause. But the same print statements reveal that sqlite version 3.32.3 is used instead on our CodeMagic build server.
I'm confused because I've just migrated from moor to drift+drift native+sqlite3_flutter_libs and expected the latter would automagically ensure the latest sqlite3 is used. It does not.
What am I missing?

Our pubspec.yaml matches https://drift.simonbinder.eu/docs/getting-started/#adding-the-dependency

Our build.yaml:
```yaml
targets:
  $default:
    sources:
      - lib/*
      - lib/src/**
      - lib/vfs/database/*
      - lib/vfs/entities/*
      - pubspec.*
      - lib/$lib$
      - $package$
      - test/test_helpers.dart
    builders:
      drift_dev:
        options:
          apply_converters_on_variables: true
          generate_values_in_copy_with: true
          named_parameters: true
          new_sql_code_generation: true
          sqlite:
            version: "3.35"
            modules:
              - fts5
```

How we create the db:
```dart
LazyDatabase _openConnection(Logger _log) {
  return LazyDatabase(() async {
    return NativeDatabase(await databaseFile(), logStatements: true,
        setup: (db) {
      db.execute('PRAGMA journal_mode = WAL');
      db.execute('PRAGMA recursive_triggers = true');
      db.execute('PRAGMA case_sensitive_like = true;');
      _log.fine('executed PRAGMA statements');
    });
  });

@DriftDatabase(include: {'tables.moor'})
class SyncDatabase extends _$SyncDatabase {
  //...

  SyncDatabase({
    MigrationListener migrationListener = const _NoopMigrationListener(),
    QueryExecutor? queryExecutor,
  })  : _migrationListener = migrationListener,
        super(queryExecutor ?? _openConnection(_log));

  // ...
}
```
