### DISCUSSION TITLE
How to setup drift for postgres?

### DISCUSSION THREAD

**Discussion by 3rpse-ai** [simolus3/drift#1870] [Q&A]
So first of all thanks for this amazing framework. I have already used it in a flutter app and appreciated it a lot.

I want to spin up an Alfred server, which I would like to connect to a Postgres db. After lots of searching for an appropriate ORM I found out that drift has experimental Postgres support which is amazing.

As a PoC I tried your most basic setup with the "Todos" & "Categories" tables. I managed to connect with my local Postgres db & create the tables (however I needed to change the ids to not use autoincremented integers as this created syntax unknown to Postgres). 

But when I try to insert a todo now it fails, printing this error:

- Drift: Sent INSERT INTO todos (id, title, body) VALUES (?, ?, ?) with args [9aebe654-20cc-47d6-9fa3-d7432a632022, Important task, Refactor persistence code]
- 2022-05-30 14:36:59.574974 - error - PostgreSQLSeverity.error 42601: syntax error at or near "," 

It seems as if the sent query is not valid Postgres syntax, however I could not find out how to change it so it would be. Would you have any hints for me?

### model.dart (poc file)
```
import 'package:drift/drift.dart';
import 'package:drift_postgres/postgres.dart';
import 'package:postgres/postgres.dart';
import 'package:uuid/uuid.dart';

part 'model.g.dart';

class Todos extends Table {
  TextColumn get id => text()
      .unique()
      .withLength(min: 32, max: 36)
      .clientDefault(() => Uuid().v4())();
  TextColumn get title => text().withLength(min: 6, max: 32)();
  TextColumn get content => text().named('body')();
  IntColumn get category => integer().nullable()();

  final test = Uuid().v4();
}

@DataClassName('Category')
class Categories extends Table {
  TextColumn get id => text()
      .unique()
      .withLength(min: 32, max: 36)
      .clientDefault(() => Uuid().v4())();
  TextColumn get description => text()();
}

@DriftDatabase(tables: [Todos, Categories])
class MyDatabase extends _$MyDatabase {
  MyDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 1;

  Future<int> addTodo() {
    return into(todos).insert(
      TodosCompanion(
        title: Value('Important task'),
        content: Value('Refactor persistence code'),
      ),
    );
  }

  Future<List<Todo>> get allTodoEntries => select(todos).get();
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final connection = PostgreSQLConnection(
      "localhost",
      5432,
      "bookable",
      username: "postgres",
    );

    return PgDatabase(connection);
  });
}
```

### pubspec.yaml
```
name: be
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  alfred: ^0.1.5+3
  uuid: ^3.0.6
  drift: ^1.6.0
  drift_postgres:
   git:
    url: https://github.com/simolus3/drift.git
    path: extras/drift_postgres

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  drift_dev: ^1.6.0
  build_runner: ^2.1.10
```
