### DISCUSSION TITLE
How to use Drift in a pure Dart console App (on Windows, with no flutter) ?

### DISCUSSION THREAD

**Discussion by 6002** [simolus3/drift#1976] [Q&A]
Hello,

Here is the contents of the pubspec.yaml file:

```yaml
name: test
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  drift: ^1.7.1
  path_provider: ^2.0.0
  path: ^1.8.2


dev_dependencies:
  test: ^1.16.0
  drift_dev: ^1.7.0
  build_runner: ^2.1.11
```

I was able to generate the tables and database classes, but when I try to run simple unit tests, I get a bunch of errors coming from a bunch of flutter packages.

It starts with "/C:/src/flutter/packages/flutter/lib/src/foundation/binding.dart:196:3: Error: Type 'ui.SingletonFlutterWindow' not found.".

So, I suspect that Drift requires Flutter.

Can someone confirm me that ?

Many thanks in advance
