### DISCUSSION TITLE
DataClass equality with Uint8Lists?

### DISCUSSION THREAD

**Discussion by sqcsabbey** [simolus3/drift#2030] [Q&A] [answered]
I'm using Uint8List id values (using ```BlobColumn```), and I don't think the equality override in the generated DataClass for my table handles these correctly. After checking identity (using ```identical```), it compares the fields with ```other.id == this.id```.  ```listEquals``` would check if they have the same value. Is there some way I can get the generated class to use listEquals instead of == for Uint8List fields?

**Comment by simolus3** [comment, marked as answer]
I think that drift should just handle this in the classes it generates. It gets kind of inefficient when you're storing _huge_ blobs in data classes, but those use cases pretty much always required some careful consideration from the end user.

I've added special support for blobs in 009056dc376633cca5b35918564c1733510eab22.

**Comment by sqcsabbey** [comment]
Is there a way I can use this with Flutter 2? I forked and I've been trying to merge, but I'm stuck, and we're stuck on Flutter 2 because of another incompatibility.

**Reply by simolus3** [reply]
You could check out the version of drift that you have been using before (just point your fork to the relevant tag) and cherry-pick the commit onto that?

**Reply by sqcsabbey** [reply]
I actually tried again, and was able to upgrade Flutter to v3; the package that didn't support it has been upgraded. 

For anyone else who sees this before this change is tagged (unlikely...), here's how I ended up specifying it in pubspec.yaml:

    dependencies:
      drift: ^2.1.0

    dev_dependencies:
      drift_dev:
        git:
          url: https://github.com/simolus3/drift
          path: drift_dev
          ref: 009056d

... drift_dev needs a hosted version of drift, but luckily these changes are in drift_dev. 


Thank you for all of your help @simolus3!

**Reply by sqcsabbey** [reply]
I think I posted that last message prematurely... what I tried doesn't work. With that setup, I'm now getting a number of errors like:


```lib/services/database/database.g.dart:1730:7: Error: The getter '$driftBlobEquality' isn't defined for the class 'Point'.
 - 'Point' is from 'package:survey/services/database/database.dart' ('lib/services/database/database.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named '$driftBlobEquality'.
      $driftBlobEquality.hash(segmentId),
      ^^^^^^^^^^^^^^^^^^
```

... and I checked, the drift package actually does need to be on the hashed version, but I can't see how to fetch that without a tag for it... if I set both to the hashed version in pubspec.yaml, I get the error:

    Because every version of drift_dev from git depends on drift from hosted and survey depends on drift from git, drift_dev from git is forbidden.

**Reply by simolus3** [reply]
As you said, both `drift` and `drift_dev` need to be overridden. A good way to do that while avoiding the pub error is to use `dependency_overrides` in your `pubspec.yaml`:

```yaml
dependency_overrides:
  drift:
      url: https://github.com/simolus3/drift
      path: drift
      ref: 009056d
  drift_dev:
      url: https://github.com/simolus3/drift
      path: drift_dev
      ref: 009056d
```

(you can just keep the regular `drift: ^2.0.0` in the `dependencies` section, same for `drift_dev` in `dev_dependencies`).

**Reply by sqcsabbey** [reply]
Does that work for you? It looks like this [bug](https://github.com/dart-lang/pub/issues/2447) (cannot depend on a git package if the git package depends on a path package) is preventing it from working, so I'm not sure if I'm missing something...

Alternatively, are you planning on tagging a new version that includes this at some point?

**Reply by simolus3** [reply]
Had a typo in my pubspec, but this one does work for me. The important part is putting the git dependencies for drift into `dependency_overrides` only.

```yaml
dependencies:
  drift: ^2.0.0

dev_dependencies:
  drift_dev: ^2.0.0
  build_runner: ^2.0.0

dependency_overrides:
  drift:
    git:
      url: https://github.com/simolus3/drift.git
      ref: 009056d
      path: drift
  drift_dev:
    git:
      url: https://github.com/simolus3/drift.git
      ref: 009056d
      path: drift_dev
```

> Alternatively, are you planning on tagging a new version that includes this at some point?

Of course, but I'm trying to get a bit more done until the next release since this probably isn't too urgent.
