### DISCUSSION TITLE
Using custom columns with drift

### DISCUSSION THREAD

**Discussion by FaFre** [simolus3/drift#2295] [Q&A] [answered]
I want to use the spatialite extension together with drift. This extension adds spatial support to sqlite, like postgis for postgres.

The extension uses specific syntax to add geometry columns, with syntax like:
```sql
create table entity (
	osm_id INTEGER PRIMARY KEY
);
select AddGeometryColumn('entity', 'bbox', 3857, 'POLYGON', 'XY');

insert into entity values(1337, GeomFromText('POLYGON((0 0, 0 1, 1 1, 1 0, 0 0))', 3857));
select bbox from entity;
```

The extension adds a very rich function set, that would be too extensive right now to add it all to drift (https://www.gaia-gis.it/gaia-sins/spatialite-sql-5.0.1.html)

However, I have already an existing project using quite a few drift tables, which I want to extend with geometry columns. I would only require drift provide me with an possibility to insert byte data returned by `GeomFromText`.  Selects would be always custom, since the column is just byte data used by spatialite (in most cases) internally.

What would be a good way to provide basic support for such a column in drift?

**Comment by simolus3** [comment, marked as answer]
I have never used spatialite, but does it really add new syntax? This is just about new functions, right? You can declare [custom functions](https://drift.simonbinder.eu/docs/advanced-features/builder_options/#known-custom-functions) as a builder option, `drift_dev` should pick those up:

```yaml
targets:
  $default:
    builders:
      drift_dev:
        options:
          sql:
            dialect: sqlite
            options:
              known_functions:
                AddGeometryColumn: "integer (text, text, int, text, text)"
```

This doesn't support variadic functions, but maybe it's good enough for your existing queries?
