### DISCUSSION TITLE
Modular drift_dev problems with blob

### DISCUSSION THREAD

**Discussion by malkue** [simolus3/drift#2306] [Q&A] [answered]
Hi, 
thanks for the great feature of modular drift files! I am using the modular builder but I have some problems generating tables containing blob data. With the normal drift_dev everything works well but with the modular builder the imports in the generated .drift.dart file are apparently not generated correctly.
```dart
import 'package:drift/drift.dart' as i0;
import 'package:drift_db/tables/test_table.drift.dart' as i1;
import 'dart:convert' as i2;

class TestTable extends i0.Table
    with i0.TableInfo<TestTable, i1.TestTableData> {
  @override
  final i0.GeneratedDatabase attachedDatabase;
  final String? _alias;
  TestTable(this.attachedDatabase, [this._alias]);
  static const i0.VerificationMeta _blobtestMeta =
      const i0.VerificationMeta('blobtest');
  late final i0.GeneratedColumn<i2.Uint8List> blobtest =
      i0.GeneratedColumn<i2.Uint8List>('blobtest', aliasedName, true,
          type: i0.DriftSqlType.blob,
          requiredDuringInsert: false,
          $customConstraints: '');
...
```
The `i2.Uint8List` is not found because it comes from `dart:typed_data` not from `dart:convert` and in the generated DataClass `$driftBlobEquality` is not found because of a missing prefix `i0`
``` dart
class TestTableData extends i0.DataClass
    implements i0.Insertable<i1.TestTableData> {
...
@override
  int get hashCode => $driftBlobEquality.hash(blobtest);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is i1.TestTableData &&
          $driftBlobEquality.equals(other.blobtest, this.blobtest));
}
```

 Is there an option in the modular drift_dev I need to set? I simply set 
```
drift_dev:modular:
        enabled: true
```
in my build.yaml but I am not quite sure what options are used in the default builder and whether I need to choose any additional options.
Many thanks in advance for any help!

**Comment by simolus3** [comment, marked as answer]
Thanks for the report! You've probably configured everything correctly, this is a bug in `drift_dev` that I've fixed in cd2cf1f3b3c35fe1bc5852d775820c50504a0805.

Does it work for you if you add this to your `pubspec.yaml`? Let me know if you run into more issues with modular code generation, if everything works I'll create a patch release with that fix:

```yaml
dependency_overrides:
  drift:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: drift
  drift_dev:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: drift_dev
  sqlparser:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: sqlparser
```
