### DISCUSSION TITLE
Issue enabling FTS

### DISCUSSION THREAD

**Discussion by powerworr** [simolus3/drift#2670] [Q&A] [answered]
Hi all, 

it seems that I'm missing something very obvious, but I've spent more time that I would like to admit on this. 

I want to enable fts5 and am using 
```
targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true
          sqlite_modules:
            - fts5
```
```
-- drift file
CREATE VIRTUAL TABLE email USING fts5(sender, title, body, dateTime);
```
```
dart run build_runner build --delete-conflicting-outputs
```

But I keep getting that the module is not enabled:
```
[WARNING] drift_dev on lib/today/data/table/tables.drift:
line 2, column 22: Drift was unable to analyze this table: Unknown module "fts5", did you register it?
  ╷
2 │ CREATE VIRTUAL TABLE email USING fts5(sender, title, body, dateTime);
  │                      ^^^^^
  ╵
```

I also tried with the snippet below, but again without success. 
```
targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true
          sql:
            dialect: sqlite
            options:
              modules:
                - fts5
```
    
What am I missing?

**Comment by simolus3** [comment, marked as answer]
Weird, the `build.yaml` configs you've posted seem to do the right thing for me. Can you check whether the `store_date_time_values_as_text` has any effect? At the end of the generated database class, there should be something like this if it is:

```dart
  @override
  DriftDatabaseOptions get options =>
      const DriftDatabaseOptions(storeDateTimeAsText: true);
``` 

Is the `.drift` file in another package than the `build.yaml` file by any chance? To see whether the options are being applied at all, you could try adding a bogus value as well:

```yaml
targets:
  $default:
    builders:
      drift_dev:
        options:
          foo: bar
```

If the build doesn't fail with that, the config is not being read.
