### DISCUSSION TITLE
Can't seem to get text based DateTime to be used

### DISCUSSION THREAD

**Discussion by piperun** [simolus3/drift#3181] [Q&A] [answered]
I'm unsure if it's something I'm doing wrong or if it's an issue with drift (I presume it's the former), but whenever I create a database where I've set an column with:
```dart
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
```
I still get unix time when I inspect the database.

I've added `build.yaml` to the root directory with the following:
```
targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true
```
as stated in:
https://drift.simonbinder.eu/docs/advanced-features/builder_options/
