### DISCUSSION TITLE
dart:ui somehow breaking `dart run drift_dev make-migrations`, any one else debug this before?

### DISCUSSION THREAD

**Discussion by kfieldi5** [simolus3/drift#3452] [General]
➜ dart run drift_dev make-migrations

Building package executable...
Built drift_dev:drift_dev.
Unhandled exception:
IsolateSpawnException: Unable to spawn isolate: ../../flutter/packages/flutter/lib/src/foundation/binding.dart:18:8: Error: Dart library 'dart:ui' is not available on this platform.
import 'dart:ui' as ui show Brightness, PlatformDispatcher, SingletonFlutterWindow, window;
       ^
Context: The unavailable library 'dart:ui' is imported through these packages:

then lists a url encoded list of every file its looking at. 

It was working a couple months ago and we've had some changes to our codebase but not so much to the database corner of the code. Curious what could have triggered this. Any help appreciated.

here is our dependencies from pubspec.yaml:

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  visibility_detector: ^0.4.0+2
  image: ^3.0.1
  audioplayers: ^6.0.0
  collection: 1.18.0
  fl_chart: ^0.69.0
  flutter_bloc: ^8.1.5
  flutter_markdown: 0.7.2+1
  freezed_annotation: ^2.4.1
  go_router: ^14.1.3
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  logging: 1.2.0
  lottie: 3.1.0
  meta: ^1.10.0
  record: ^5.1.2
  rive: ^0.13.20
  rxdart: 0.27.7
  scrollable_positioned_list: 0.3.8
  web_socket_channel: 3.0.1
  path_provider: ^2.1.3
  drift: ^2.21.0
  sqlcipher_flutter_libs: ^0.6.0
  path: ^1.9.0
  datadog_flutter_plugin: ^2.7.0
  webview_flutter: ^4.10.0
  synchronized: ^3.3.0+3
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.11
  pigeon: ^14.0.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  golden_toolkit: ^0.15.0
  fake_http_client: ^1.0.0
  yaml: ^3.1.2
  test: ^1.25.7
  drift_dev: ^2.21.0
  sqlite3: ^2.4.7
  webview_flutter_platform_interface: ^2.10.0
  ```

Thanks
