### ISSUE TITLE
Add information about direct and transitive dependencies for iOS and SQLCipher

### ISSUE THREAD

**Issue by cremfert** [simolus3/drift#1480]
When working with iOS and SQLCipher with drift:ffi, other libraries like cached_network_image will override sqlite with their own version, leading to a conflict when using SQLCipher. As a result, the SQLite file couldn't be opened and might get corrupted.

Details can be found here: https://github.com/simolus3/moor/discussions/1479

@davidmartos96 provided a solution for this problem here:
https://github.com/davidmartos96/sqflite_sqlcipher/blob/master/sqflite/README.md#if-using-sqflite-as-direct-or-transitive-dependency

```
dependency_overrides:
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: fmdb_override
```

I suggest to put this in the docs as well because it took a lot of time to figure this out. Besides that, thanks for this great library!
