### ISSUE TITLE
Gradle project sync failed . Basic functionality ( e . g . editing , debugging ) will not work properly .

### ISSUE THREAD

**Issue by ddxl123** [simolus3/drift#1722]
build log:
```
The option setting 'android.enableR8=true' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8
Affected Modules: sqlite3_flutter_libs
```
`Affected Modules: sqlite3_flutter_libs` I suspect it is drift's problem. 

```
  sqflite 2.0.2
  sqflite_common 2.2.0
  sqlite3 1.5.1
  sqlite3_flutter_libs 0.5.4
  drift 1.4.0
  drift_dev 1.4.0
```

**Comment by simolus3** [comment]
I don' think the `enableR8=true` will cause the gradle sync to break, but nevertheless it shouldn't be enabled explicitly.

Can you add this to your pubspec and see if the warnings go away?

```yaml
dependency_overrides:
  sqlite3_flutter_libs:
    git:
      url: https://github.com/simolus3/sqlite3.dart.git
      ref: main
      path: sqlite3_flutter_libs/
```

If they don't, can you try to build the app (`flutter run` on Android should work) and post the error message if that fails?
