### ISSUE TITLE
Documentation issue: Getting started

### ISSUE THREAD

**Issue by tofutim** [simolus3/drift#1736]
I wanted to explore drift today but ran into the following issue in "Getting Started". With the following:
```
dependencies:
  flutter:
    sdk: flutter
  drift: ^1.4.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^1.4.0
  build_runner: ^2.1.7
```
I got the error below:

> [alfa] flutter pub get
> Running "flutter pub get" in alfa...                            
> Because every version of flutter_test from sdk depends on path 1.8.0 and alfa depends on path ^1.8.1, flutter_test from sdk is forbidden.
> So, because alfa depends on flutter_test from sdk, version solving failed.
> pub get failed (1; So, because alfa depends on flutter_test from sdk, version solving failed.)
> exit code 1

Probably related to this: https://github.com/dart-lang/path/issues/115

On this end, 
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.6 20G165 darwin-x64, locale
    en-US)

**Update.** In the interim, I have circumvented the issue by using path ^1.8.0
