### ISSUE TITLE
moor_shared fails on Linux platform with `Failed to load dynamic library 'libsqlite3.so': `

### ISSUE THREAD

**Issue by ValeriusGC** [simolus3/drift#1763]
Hi. Sample `moor_shared` works well on Android but crashes on Linux with 
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libsqlite3.so': libsqlite3.so: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      _defaultOpen (package:sqlite3/src/load_library.dart:27:29)
#3      OpenDynamicLibrary.openSqlite (package:sqlite3/src/load_library.dart:122:12)
#4      sqlite3 (package:sqlite3/src/api/sqlite3.dart:10:38)
#5      _VmDelegate._createDatabase (package:drift/src/ffi/database.dart:169:13)
#6      _VmDelegate.open (package:drift/src/ffi/database.dart:148:7)
#7      DelegatedDatabase.ensureOpen.<anonymous closure> (package:drift/src/runtime/executor/helpers/engines.dart:301:22)
```

**flutter doctor**
```
[✓] Flutter (Channel stable, 2.10.3, on Ubuntu 20.04.4 LTS 5.13.0-35-generic, locale en_US.UTF-8)
    • Flutter version 2.10.3 at /home/vvk/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (2 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Linux (desktop)                    • linux         • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-35-generic
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 99.0.4844.51
```

**My YAML**
```
environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dart
  cupertino_icons: ^1.0.4
  moor: ^4.6.1+1
  rxdart: ^0.27.3
  intl: ^0.17.0

  # Also use the latest version.
  sqlite3_flutter_libs: ^0.5.4

  # Helper to find the database path on mobile
  path_provider: ^2.0.9
  path: 1.8.0
  undo: ^1.4.0

  moor_db_viewer: ^5.0.0
  
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

dev_dependencies:
  moor_generator: ^4.6.0+1
  build_runner: ^2.1.8
  build_web_compilers: ^3.2.2
  flutter_test:
    sdk: flutter

```
