### ISSUE TITLE
moor_shared does not save changes in Web

### ISSUE THREAD

**Issue by ValeriusGC** [simolus3/drift#1764]
Hi!
When i change data, then stop and start Chrome (Web) target again there are no my changes, they are lost.

**flutter doctor:**
```
/home/vvk/snap/flutter/common/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 2.10.3, on Ubuntu 20.04.4 LTS 5.13.0-35-generic, locale en_US.UTF-8)
    • Flutter version 2.10.3 at /home/vvk/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (2 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
    • Android SDK at /home/vvk/Android/Sdk
    • Platform android-31, build-tools 31.0.0-rc1
    • Java binary at: /snap/android-studio/119/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.1)
    • Android Studio at /snap/android-studio/119/android-studio
    • Flutter plugin version 65.2.2
    • Dart plugin version 211.7808
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Linux (desktop)                    • linux         • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-35-generic
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
Process finished with exit code 0
```

**yaml**
```
environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dart
  cupertino_icons: ^1.0.4
  moor: ^4.6.1+1
  rxdart: ^0.27.3
  intl: ^0.17.0

  # Also use the latest version.
  sqlite3_flutter_libs: ^0.5.4

  # Helper to find the database path on mobile
  path_provider: ^2.0.9
  path: 1.8.0
  undo: ^1.4.0

  moor_db_viewer: ^5.0.0
  
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

dev_dependencies:
  moor_generator: ^4.6.0+1
  build_runner: ^2.1.8
  build_web_compilers: ^3.2.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

```
