### ISSUE TITLE
Force quiting our app throws `file is not a database` error at startup of the app

### ISSUE THREAD

**Issue by vanlooverenkoen** [simolus3/drift#1810]
We are using an encrypted database but I found that when using a long encryption key it is possible to find other combinations that will decrypt the database.

Db key =  `3d80ac84-6dff-40bb-b803-abeed6c5e297`

`3d80ac84-6dff-40bb-b803-abeed6c5e297` + `test` -> :white_check_mark:
`test`  + `3d80ac84-6dff-40bb-b803-abeed6c5e297` + `test`  -> :x:
`test ` + `3d80ac84-6dff-40bb-b803-abeed6c5e297` -> :x:
`3d80ac84-6dff-4` -> :x:
`3d80ac84-6dff-40` -> :white_check_mark:

It seems that the max lenght for the encryption pragma key is 16. Other chars will be ignored. If this is intended behaviour this should be documented somewhere

**Comment by simolus3** [comment]
This sounds worrying - SQLCipher uses PBKDF2 to derive the key from a string, so it shouldn't consider a subset of the key only. This is definitely

On what platforms are you running into this? I can't reproduce this on Android with this driver test:

```dart
  test('key test', () async {
    final dir = await getApplicationDocumentsDirectory();
    dir.createSync();
    final file = File('${dir.path}/test.db');
    if (file.existsSync()) file.deleteSync();

    var db = sqlite3.open('${dir.path}/test.db');

    void reOpen() {
      db.dispose();
      db = sqlite3.open('${dir.path}/test.db');
    }

    db.execute("PRAGMA key = '3d80ac84-6dff-40bb-b803-abeed6c5e297'");
    db.execute('create table foo (bar);');
    reOpen();

    db.execute("PRAGMA key = '3d80ac84-6dff-40bb-b803-abeed6c5e297test'");
    expect(
        () => db.execute('select * from foo;'),
        throwsA(isA<SqliteException>()
            .having((e) => e.message, 'message', 'file is not a database')));
  });
```

I tried running this and it gave me the expected exception.

**Comment by vanlooverenkoen** [comment]
I have been testing on iOS today. Tomorrow I will do android. We do have a could apps that use this implementation with 8 million users. But they are all still using `moor`. Tomorrow I will do some extra checks & check out the moor implementation of our other projects. Maybe I did forget something when migrating from moor to drift

**Comment by North101** [comment]
> Same test works for me in the iOS simulator, I don't have an actual device to test on unfortunately. Let me know if there's more I can try out, so far I've only tested the underlying `sqlite3` package but I don't think moor/drift would cause this as custom statements are directly passed down to that package.

Could it be a difference between sqflite vs flutter_sql_libs?

**Comment by davidmartos96** [comment]
The iOS sqflite_sqlcipher implementation uses the FMDB library.

**Comment by simolus3** [comment]
@vanlooverenkoen Are you using `encrypted_moor` or the `VmDatabase`/`NativeDatabase` backend with `sqlcipher_flutter_libs`? I can test the other one too (but it would surprise me if they somehow cut the key pragma).

**Comment by vanlooverenkoen** [comment]
We are using NativeDatabase

**Comment by vanlooverenkoen** [comment]
We are also using isolates, maybe that has something to do with it?

**Comment by vanlooverenkoen** [comment]
Just tested on our application with 8 million users. (using moor). It does throw an error `file not a database` when adding `test` at the end.

I am now trying to figure out what the difference is between 2 codebases.

**Comment by vanlooverenkoen** [comment]
The issue is happening on android & iOS

**Comment by vanlooverenkoen** [comment]
```
  final executor = NativeDatabase(
    File(request.targetPath),
    logStatements: true,
    setup: (db) async {
      final cipherVersion = db.select('PRAGMA cipher_version;');
      if (cipherVersion.isEmpty) {
        print('No cipher version');
      } else {
        print(cipherVersion.first);
      }
      db.execute("PRAGMA key = '${request.password}';");
    },
  );
```

@simolus3 is it normal that I get `no cipher version` here?

**Comment by vanlooverenkoen** [comment]
I also can't open my sqlite db in table plus. A password is requested. but after entering the password I can't do anything.
No select
Don't see any tables

**Comment by simolus3** [comment]
> We are also using isolates, maybe that has something to do with it?

Isolates shouldn't have an impact on this.

> is it normal that I get `no cipher version` here?

Absolutely not! I means that the database is running against the regular sqlite3 implementation instead of SQLCipher. That would also explain why the `key` pragma isn't doing anything. If you're getting a "file is not a database" error _sometimes_, it sounds like you're not always getting the SQLCipher implementation at runtime.

Just to be sure, you're using `open.overrideFor(OperatingSystem.android, openCipherOnAndroid)` on Android, right? And you're also doing this on _all_ isolates where you're opening a database connection?

On iOS, you might have another pod linking the regular sqlite3 library. Linking both SQLCipher and sqlite3 into the same executable leads to undefined behavior (which could include a broken mixture of both libraries). Could you check something [like this](https://discuss.zetetic.net/t/important-advisory-sqlcipher-with-xcode-8-and-new-sdks/1688)? (unfortunately I don't have too much native iOS development experience).

**Comment by vanlooverenkoen** [comment]
This is our current implementation

```
import 'dart:ffi';
import 'dart:io';
import 'dart:isolate';

import 'package:drift/drift.dart';
import 'package:drift/isolate.dart';
import 'package:drift/native.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:my_app/repository/secure_storage/auth/auth_storage.dart';
import 'package:my_app/util/env/flavor_config.dart';
import 'package:icapps_architecture/icapps_architecture.dart';
import 'package:path/path.dart';
import 'package:path_provider/path_provider.dart';
import 'package:sqlcipher_flutter_libs/sqlcipher_flutter_libs.dart';
import 'package:sqlite3/open.dart';

Future<DatabaseConnection> createDriftDatabaseConnection(AuthStorage authStorage, String name) async {
  if (FlavorConfig.isInTest()) {
    return DatabaseConnection.fromExecutor(NativeDatabase.memory());
  }
  final dbFolder = await getApplicationDocumentsDirectory();
  final dbName = '$name.sqlite';
  final file = File(join(dbFolder.path, dbName));
  final dbKey = await authStorage.databaseKey;
  staticLogger.debug('DB Key: $dbKey');
  await FirebaseCrashlytics.instance.log('DB Key: $dbKey');
  final receivePort = ReceivePort();
  await applyWorkaroundToOpenSqlCipherOnOldAndroidVersions();
  await Isolate.spawn(
    _startBackground,
    _IsolateStartRequest(receivePort.sendPort, file.path, dbKey),
  );

  final isolate = await receivePort.first as DriftIsolate;
  return isolate.connect();
}

Future<void> _startBackground(_IsolateStartRequest request) async {
  if (Platform.isIOS) {
    open.overrideFor(OperatingSystem.iOS, DynamicLibrary.process);
  } else if (Platform.isAndroid) {
    await applyWorkaroundToOpenSqlCipherOnOldAndroidVersions();
    open.overrideFor(OperatingSystem.android, openCipherOnAndroid);
  }

  final executor = NativeDatabase(
    File(request.targetPath),
    logStatements: true,
    setup: (db) => db.execute("PRAGMA key = '${request.password}'"),
  );
  final isolate = DriftIsolate.inCurrent(
    () => DatabaseConnection.fromExecutor(executor),
  );
  request.sendIsolate.send(isolate);
}

class _IsolateStartRequest {
  final SendPort sendIsolate;
  final String targetPath;
  final String password;

  _IsolateStartRequest(
    this.sendIsolate,
    this.targetPath,
    this.password,
  );
}
```

**Comment by vanlooverenkoen** [comment]
This is what is added in our `podfile.lock`
```
  - sqflite (0.0.2):
    - Flutter
    - FMDB (>= 2.7.5)
  - SQLCipher (4.5.1):
    - SQLCipher/standard (= 4.5.1)
  - SQLCipher/common (4.5.1)
  - SQLCipher/standard (4.5.1):
    - SQLCipher/common
  - sqlcipher_flutter_libs (0.0.1):
    - Flutter
    - SQLCipher (~> 4.5.0)
```
```

dependencies:
  device_info_plus: ^3.2.2
  dio: ^4.0.6
  bot_toast: ^4.0.1
  devicelocale: ^0.5.0
  drift: ^1.5.0
  file_local_storage_inspector: ^0.2.3
  firebase_analytics: ^9.1.5
  firebase_core: ^1.14.1
  firebase_crashlytics: ^2.6.2
  firebase_messaging: ^11.2.13
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_html: ^3.0.0-alpha.2
  flutter_inappwebview: ^5.4.0+1
  flutter_localizations:
    sdk: flutter
  flutter_multi_formatter: ^2.5.1
  flutter_secure_file_storage: ^0.0.7
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.3
  get_it: ^7.2.0
  icapps_architecture: ^0.6.4
  in_app_update: ^3.0.0
  injectable: ^1.5.3
  jose: ^0.3.2
  json_annotation: ^4.4.0
  lottie: ^1.3.0
  modal_bottom_sheet: ^2.0.1
  niddler_dart: ^1.4.1
  package_info_plus: ^1.4.2
  path: ^1.8.0
  path_provider: ^2.0.9
  preferences_local_storage_inspector: ^0.2.3
  provider: ^6.0.2
  open_settings: 2.0.2
  retrofit: ^3.0.1+1
  scroll_when_needed: ^2.0.0
  secure_storage_local_storage_inspector: ^0.2.3
  shared_preferences: ^2.0.13
  share_plus: ^4.0.4
  signed_json: ^0.0.2
  sms_autofill: ^2.2.0
  sqlcipher_flutter_libs: ^0.5.1
  storage_inspector: ^0.2.3
  synchronized: ^3.0.0+2
  url_launcher: ^6.0.20
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.10
  drift_dev: ^1.5.2
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  icapps_translations: ^5.2.1
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.6
  license_generator: ^1.0.3
  mockito: ^5.1.0
  model_generator: ^5.8.1
  retrofit_generator: ^4.0.1

```
