### ISSUE TITLE
MissingPluginException: No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider_macos

### ISSUE THREAD

**Issue by iChintanSoni** [simolus3/drift#1822]
**Describe the bug**

I am trying to write a test case for Drift Dao. While I run test case, I am seeing below error:

```
MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider_macos)
package:flutter/src/services/platform_channel.dart 165:7                     MethodChannel._invokeMethod
===== asynchronous gap ===========================
dart:async                                                                   _completeOnAsyncError
package:database/database.dart                                               _openConnection.<fn>
===== asynchronous gap ===========================
dart:async                                                                   Future.then
package:drift/src/utils/lazy_database.dart 32:27                             LazyDatabase._awaitOpened
package:drift/src/utils/lazy_database.dart 46:12                             LazyDatabase.ensureOpen
package:drift/src/runtime/api/connection_user.dart 160:21                    DatabaseConnectionUser.doWhenOpened
package:drift/src/runtime/query_builder/statements/select/select.dart 67:21  SimpleSelectStatement._getRaw
package:drift/src/runtime/query_builder/statements/select/select.dart 51:12  SimpleSelectStatement.get
package:database/user/user_dao.dart 15:41              UserDao.allUsers
test/database_test.dart 22:34                                                main.<fn>
test/database_test.dart 14:31                                                main.<fn>
```

**database_test.dart:**
```
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  
  test('test database fetch', () async {
    startKoin((app) {
      app.module(databaseModule);
    });
    UserDao userDao = get<UserDao>();
    List<User> userList =
        await userDao.allUsers;
    print("List Size: ${userList.length}");
  });
}
```

**database_di.dart:**
```
final databaseModule = Module()
  ..single((s) => SomeDB())
  ..single((s) => s.get< SomeDB >().userDao);
```

**database.dart:**
```
import 'dart:io';
import 'package:database/user/user.dart';
import 'package:database/user/user_dao.dart';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

part 'database.g.dart';

@DriftDatabase(tables: [Users], daos: [UserDao])
class SomeDb extends _$SomeDb {
  SomeDb() : super(_openConnection());

  @override
  int get schemaVersion => 1;

  Future<void> deleteAllData() {
    return transaction(() async {
      for (var table in allTables) {
        await delete(table).go();
      }
    });
  }
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'db.sqlite'));
    return NativeDatabase(file);
  });
}
```

**pubspec.yaml:**
```
name: database
description: This layer serves as datasource from the local environment
version: 0.0.1
homepage: 

environment:
  sdk: ">=2.17.0-266.5.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  drift:
  sqlite3_flutter_libs:
  path_provider:
  path:
  koin: "0.15.0-nullsafety.0"
  koin_flutter:

dev_dependencies:
  koin_test: "0.13.0-nullsafety.0"
  flutter_test:
    sdk: flutter
  flutter_lints:
  drift_dev:
  build_runner:
```

Can someone help me with this? Let me know if some more details.
