### ISSUE TITLE
Unknown column

### ISSUE THREAD

**Issue by the4thfloor** [simolus3/drift#1858]
I was in need to manually override the SQLite version, see https://github.com/simolus3/drift/issues/1857

Since this change, I get this warning:
```
[WARNING] drift_dev:drift_dev on lib/src/database/database.dart:
line 708, column 20: Unknown column. These columns are available: key, value, type, atom, type, id, parent, fullkey
    ╷
708 │              WHERE position_id = json_extract(j.value, '$.positionid')
    │                    ^^^^^^^^^^^
    ╵
```

This is the table definition:
```sql
CREATE TABLE IF NOT EXISTS contract_has_add_fees
(
   position_id INTEGER NOT NULL,
   position_db INTEGER NOT NULL,
   addfee      TEXT    NOT NULL,
   amount      REAL    NOT NULL,
   changed     DATETIME,
   removed     BOOLEAN NOT NULL DEFAULT FALSE,
   PRIMARY KEY (position_id, position_db, addfee),
   FOREIGN KEY (position_id, position_db) REFERENCES contracts ON DELETE CASCADE
) WITHOUT ROWID;
```

And this is my query where the warning happens:
```sql
deleteAllContractHasAddfees:
DELETE
FROM contract_has_add_fees
WHERE EXISTS(SELECT *
             FROM json_each(:json) AS j
             WHERE position_id = json_extract(j.value, '$.positionid')
               AND position_db = json_extract(j.value, '$.positiondb')
               AND addfee = json_extract(j.value, '$.addfee')
         );
```

But it is just a warning, everything works.

**Comment by simolus3** [comment]
Thanks for the report, I can reproduce this locally. It seems like the error doesn't happen if you add a table alias:

```sql
DELETE
FROM contract_has_add_fees d
WHERE EXISTS(SELECT *
             FROM json_each(:json) AS j
             WHERE d.position_id = json_extract(j.value, '$.positionid')
               AND d.position_db = json_extract(j.value, '$.positiondb')
               AND d.addfee = json_extract(j.value, '$.addfee')
```

I'll take a look at why these columns aren't available by default.

**Comment by simolus3** [comment]
Quick update: This is turning out to be a lot harder than I expected it to be :D

The problem is that, at the moment, `sqlparser` assumes that only columns to which a `*` would expand to can be referenced without an explicit table name. But in the inner select, the `*` expands to the columns of `json_each` and you can still refer to outer columns. Fixing this caused all kinds of other problems because the way column lookups are currently implemented in `sqlparser`. I've started refactoring this, but the implementation is pretty complicated and I need to make sure it doesn't break anything else.

**Comment by the4thfloor** [comment]
Please no pressure, the workaround is fine for me.

**Comment by simolus3** [comment]
Should be good now! If you want to, you could try adding this to your pubspec and running the build again:

```yaml
dependency_overrides:
  drift:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: drift
  drift_dev:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: drift_dev
  sqlparser:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: sqlparser
```

There are lots of internal tests around reference handling but as this issue and others have shown, it's a tricky thing to get exactly right. If anything new breaks (new warnings, changes in generated code) for you with these git overrides, please let me know.
