### ISSUE TITLE
Generator barfs when using a DAO

### ISSUE THREAD

**Issue by ndawod** [simolus3/drift#781]
I've been through this for hours, and everything seems to be done by the book -- but I'm afraid that something is not working with Flutter 2.10 (with nullability) and recent Moor version.

Details of everything below:

doctor -v output:
```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.36, on Linux, locale en_US.utf8)
    • Flutter version 1.22.0-2.0.pre.36 at ~/Google/Flutter
    • Framework revision d30e36ba8c (12 hours ago), 2020-08-21 22:36:03 -0400
    • Engine revision d495da20d0
    • Dart version 2.10.0 (build 2.10.0-49.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /opt/google/android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /opt/google/android/sdk
    • Java binary at: /opt/google/android/studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /opt/google/android/studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /opt/jetbrains/idea-IU-193.6015.39
    • Flutter plugin version 45.0.2
    • Dart plugin version 193.6911.31

[✓] Connected device (5 available)
    • Nexus 5 (mobile)                      • XXXXXXXX • android-arm    • Android 6.0.1 (API 23)
    • Pixel 3a (mobile)                     • XXXXXXXX       • android-arm64  • Android 10 (API 29)
    • Android SDK built for x86 64 (mobile) • emulator-5554    • android-x64    • Android 6.0 (API 23) (emulator)
    • Web Server (web)                      • web-server       • web-javascript • Flutter Tools
    • Chrome (web)                          • chrome           • web-javascript • Google Chrome 84.0.4147.125

• No issues found!
```

pubspec.yaml (relevant parts):
```
environment:
    sdk: ">=2.10.0-49.0.dev <3.0.0"

dependencies:
    flutter:
        sdk: "flutter"

    flutter_localizations:
        sdk: "flutter"

    # https://pub.dev/packages/sqflite
    sqflite: "1.3.1"

    # https://pub.dev/packages/moor
    moor: "3.3.1"

    # https://pub.dev/packages/moor_flutter
    moor_flutter: "3.1.0"

dev_dependencies:
    # https://pub.dev/packages/pedantic
    pedantic: "1.9.2"

    # https://pub.dev/packages/build_runner
    build_runner: "1.10.2"

    # https://pub.dev/packages/moor_generator
    moor_generator: "3.3.1"

dependency_overrides:
    # The Analyzer must be compatible with null-safety and align with the SDK's version.
    analyzer: "0.40.0"
```

main.dart:
```dart
import 'package:moor_flutter/moor_flutter.dart';

part 'main.g.dart';

@UseMoor(
  daos: [TodoDao],
  tables: [Todo],
)
class GlobalDatabase extends _$GlobalDatabase {
  GlobalDatabase(this.filePath, {bool logging = false})
      : super(FlutterQueryExecutor(
          path: filePath,
          logStatements: logging,
        ));

  final String filePath;

  @override
  int get schemaVersion => 1;
}

@UseDao(
  include: {'todo.moor'},
  tables: [Todo],
)
class TodoDao extends DatabaseAccessor<GlobalDatabase> with _$TodoDaoMixin {
  TodoDao._(GlobalDatabase db) : super(db);
}
```

Trace:
```
[SEVERE] moor_generator:moor_generator on lib/src/db/global/main.dart (cached):

Failed assertion: boolean expression must not be null
package:analyzer/src/dart/element/display_string_builder.dart 250:9             ElementDisplayStringBuilder._writeNullability
package:analyzer/src/dart/element/display_string_builder.dart 151:5             ElementDisplayStringBuilder.writeInterfaceType
package:analyzer/src/dart/element/type.dart 840:13                              InterfaceTypeImpl.appendTo
package:analyzer/src/dart/element/type.dart 1696:5                              TypeImpl.getDisplayString
package:moor_generator/src/writer/database_writer.dart 76:28                    DatabaseWriter.write
package:moor_generator/src/backends/build/generators/moor_generator.dart 36:42  MoorGenerator.generate
package:source_gen/src/builder.dart 301:33                                      _generate
package:source_gen/src/builder.dart 79:15                                       _Builder._generateForLibrary
package:source_gen/src/builder.dart 71:11                                       _Builder.build
package:moor_generator/src/backends/build/moor_builder.dart 87:18               MoorSharedPartBuilder.build
package:build                                                                   runBuilder
package:build_runner_core/src/generate/build_impl.dart 486:19                   _SingleBuild._runForInput.<fn>.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 302:15          _NoOpBuilderActionTracker.trackStage
package:build_runner_core/src/generate/build_impl.dart 484:23                   _SingleBuild._runForInput.<fn>.<fn>
package:build_runner_core/src/generate/build_impl.dart                          _SingleBuild._runForInput.<fn>.<fn>
package:timing/src/timing.dart 222:44                                           NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 441:22                   _SingleBuild._runForInput.<fn>
package:pool/pool.dart 127:28                                                   Pool.withResource
package:build_runner_core/src/generate/build_impl.dart 437:17                   _SingleBuild._runForInput
package:build_runner_core/src/generate/build_impl.dart 375:38                   _SingleBuild._runBuilder.<fn>
dart:async                                                                      Future.wait
package:build_runner_core/src/generate/build_impl.dart 374:36                   _SingleBuild._runBuilder
package:build_runner_core/src/generate/build_impl.dart 320:20                   _SingleBuild._runPhases.<fn>.<fn>
dart:async                                                                      _completeOnAsyncReturn
package:build_runner_core/src/generate/build_impl.dart                          _SingleBuild._matchingPrimaryInputs

[SEVERE] Build:
```

It seems that the `nullabilitySuffix` is `null`, traced back this line from the `database_writer.dart:76`:

```dart
final typeName = dao.getDisplayString();
```

Is there anything I'm doing wrong or I just uncovered a bug?
